### ISSUE TITLE
Fallo al editar 2 veces a la persona o crear y luego editar

### ISSUE THREAD

**Issue by Gonzalo89** [rodrif/RecorridasZOTP#49]
Fallo al editar 2 veces a la persona o crear y luego editar, el segundo edit no surge efecto, ya que se reciben los datos del primer edit en estado actualizado y por eso no manda el segundo edit.

Posible problema con la hora

Pasos:

1. Editar persona
2. Sincronizar
3. Editar persona

**Comment by rodrif** [comment]
Arreglado. Probar

**Comment by Gonzalo89** [comment]
Probado
