### ISSUE TITLE
No se refleja en cambio de ranchada en android

### ISSUE THREAD

**Issue by rodrif** [rodrif/RecorridasZOTP#52]
1 crear una nueva ranchada desde la web
2 cambiar a una persona a esa ranchada

se ve reflejado el cambio en la web, pero no en android
Para ranchadas existentes en haedo, anda bien.
Parece ser xq haedo es justo la primer zona, las ranchadas de las demas zonas no andan
Lo mismo pasa con familia

**Comment by rodrif** [comment]
probar

**Comment by Gonzalo89** [comment]
Probado
